# 提权操作
ansible_become: true
# 安装模式
install_mode: online

# 当前节点ip
CURRENT_HOST_IP: "{% if hostvars[inventory_hostname]['ansible_host'] is defined %}{{ hostvars[inventory_hostname]['ansible_host'] }}{% else %}{{ inventory_hostname }}{% endif %}"
lb_mode: "nginx"
# apiserver ip
KUBE_APISERVER_IP: >-
  {% if lb_kube_apiserver_ip is not defined %}
    127.0.0.1
  {% else %}
    {{ lb_kube_apiserver_ip }}
  {% endif %}

# 加入集群token
kubeadm_token: "abcdef.0123456789abcdef"

# 负载后的apiserver端口号
lb_kube_apiserver_port: 8443

# Kubelet 根目录
kubelet_root_dir: "/var/lib/kubelet"
# Pod根容器
pod_infra_container_image: gcr.azk8s.cn/google_containers/pause:3.1
# node节点最大pod 数
kube_max_pods: 110
# 资源保留相关配置
eviction_hard_imagefs_available: 15%
eviction_hard_memory_available: 100Mi
eviction_hard_nodefs_available: 10%
eviction_hard_nodefs_inodes_free: 5%
# kubernetes各组件镜像仓库前缀
kube_image_repository: gcr.azk8s.cn/google_containers
# kubernetes版本
kube_version: 1.15.7
# 集群内部dns域名
kube_dns_domain: cluster.local
# 集群pod ip段
kube_pod_subnet: 10.244.0.0/18
# 集群service ip段
kube_service_subnet: 10.244.64.0/18

CLUSTER_DNS_SERVICE_IP: "{{ kube_service_subnet | ipaddr('net') | ipaddr(10) | ipaddr('address') }}"