language: python 
services:
  - docker
install: true
jobs:
  include:
    - stage: build
      script:
        - |
          cat << EOF >config.yaml
          from:
            registry: https://registry-1.docker.io
          to:
            registry: https://registry.aliyuncs.com
          names:
            - library/nginx:1.19-alpine
            - library/haproxy:2.1-alpine
            - library/traefik:2.3.1
            - openresty/openresty:1.17.8.2-alpine
            - envoyproxy/envoy:v1.16.0
            - osixia/keepalived:2.0.20
            - calico/typha
            - calico/cni
            - calico/node
            - calico/kube-controllers
            - calico/pod2daemon-flexvol
            - calico/ctl
            - jettech/kube-webhook-certgen
            - kubernetesui/dashboard
            - kubernetesui/metrics-scraper
          replace:
            - old: openresty/
              new: kubeadm-ha/openresty_
            - old: envoyproxy/
              new: kubeadm-ha/envoyproxy_
            - old: osixia/
              new: kubeadm-ha/osixia_
            - old: calico/
              new: kubeadm-ha/calico_
            - old: jettech/
              new: kubeadm-ha/jettech_
            - old: kubernetesui/
              new: kubeadm-ha/kubernetesui_
            - old: library
              new: kubeadm-ha
          rules:
            - ^[Vv]?\d+\.\d+(\.\d+)?(-\d+)?$
          EOF
          docker run -v $PWD/config.yaml:/config.yaml \
          setzero/images-sync:0.3.1 \
          /bin/sh -c "TO_USERNAME=$TO_USERNAME TO_PASSWORD=$TO_PASSWORD sync-images --config config.yaml"

    - stage: build
      script:
        - |
          cat << EOF >config.yaml
          from:
            registry: https://quay.io
          to:
            registry: https://registry.aliyuncs.com
          names:
            - coreos/flannel
            - jetstack/cert-manager-cainjector
            - jetstack/cert-manager-webhook
            - jetstack/cert-manager-controller
          replace:
            - old: coreos/
              new: kubeadm-ha/coreos_
            - old: jetstack/
              new: kubeadm-ha/jetstack_
          rules:
            - ^[Vv]?\d+\.\d+(\.\d+)?(-\d+)?$
          EOF
          docker run -v $PWD/config.yaml:/config.yaml \
          setzero/images-sync:0.3.1 \
          /bin/sh -c "TO_USERNAME=$TO_USERNAME TO_PASSWORD=$TO_PASSWORD sync-images --config config.yaml"

    - stage: build
      script:
        - |
          cat << EOF >config.yaml
          from:
            registry: https://k8s.gcr.io
          to:
            registry: https://registry.aliyuncs.com
          names:
            - kube-apiserver
            - kube-controller-manager
            - kube-scheduler
            - kube-proxy
            - pause
            - etcd
            - coredns
            - ingress-nginx/controller
            - metrics-server/metrics-server
          replace:
            - old: ingress-nginx/
              new: kubeadm-ha/ingress-nginx_
            - old: metrics-server/
              new: kubeadm-ha/metrics-server_
            - new: kubeadm-ha
          rules:
            - ^[Vv]?\d+\.\d+(\.\d+)?(-\d+)?$
          EOF
          docker run -v $PWD/config.yaml:/config.yaml \
          setzero/images-sync:0.3.1 \
          /bin/sh -c "TO_USERNAME=$TO_USERNAME TO_PASSWORD=$TO_PASSWORD sync-images --config config.yaml"