version: 2
jobs:
  build:
    docker:
      - image: docker:18.09.3-git
    steps:
      - setup_remote_docker:
          version: 18.09.3
      - checkout
      - run : |
          # export COMMIT_SHA=$(git log -1 --pretty=format:"%H" | awk '{print substr($1,1,8)}') 
          # docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD
          # docker build --build-arg COMMIT_SHA=${COMMIT_SHA} -t setzero/kubeadm-ha:${CIRCLE_BRANCH}-${COMMIT_SHA} .
          # docker push setzero/kubeadm-ha:${CIRCLE_BRANCH}-${COMMIT_SHA}

          image_list="
          openresty/openresty:1.15.8.3-alpine
          nginx:1.17.9-alpine
          haproxy:2.1.3-alpine
          envoyproxy/envoy-alpine:v1.13.1
          osixia/keepalived:2.0.20
          registry.access.redhat.com/rhel7/pod-infrastructure:latest
          quay.io/coreos/flannel:v0.12.0-amd64
          calico/typha:v3.13.1
          calico/cni:v3.13.1
          calico/node:v3.13.1
          calico/kube-controllers:v3.13.1
          calico/pod2daemon-flexvol:v3.13.1
          calico/ctl:v3.13.1
          quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.30.0
          traefik:1.7.19
          kubernetesui/dashboard:v2.0.0-rc6
          kubernetesui/metrics-scraper:v1.0.3
          quay.io/jetstack/cert-manager-cainjector:v0.9.1
          quay.io/jetstack/cert-manager-webhook:v0.9.1
          quay.io/jetstack/cert-manager-controller:v0.9.1
          setzero/ansible:2.8.5-nginx-1.17.6-alpine
          "
          
          new_docker_registry=${NEW_DOCKER_REGISTRY:-'registry.cn-shanghai.aliyuncs.com/kubeadm-ha'}
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ${new_docker_registry%%/*}
          for image in $image_list ; do 
            count=$(echo $image | grep -o '/*' | wc -l)
            if [ $count -eq 0 ]
            then
              new=$new_docker_registry/$image
            elif [ $count -eq 1 ]
            then
              new=$new_docker_registry/$(echo ${image} | sed 's / _ g')
            else
              new=$new_docker_registry/$(echo ${image#*/} | sed 's / _ g')
            fi
            echo "FROM $image" > Dockerfile
            docker build -t $new .
            docker push $new
          done
workflows:
  version: 2
  build:
    jobs:
    - build