# 根据stat信息判断是否已经生成过kubernetes证书，如果没有，下一步生成证书
# 如果已经有kubernetes证书，为了保证整个安装的幂等性，跳过证书生成的步骤
- name: 读取 kubernetes-ca 根证书私钥 stat 信息
  stat: 
    path: /etc/kubernetes/pki/ca.key
  register: ca_key_stat

- name: 读取 kubernetes-ca 根证书 stat 信息
  stat: 
    path: /etc/kubernetes/pki/ca.crt
  register: ca_crt_stat

- name: 读取 front-proxy-ca 根证书私钥 stat 信息
  stat: 
    path: /etc/kubernetes/pki/front-proxy-ca.key
  register: front_proxy_ca_key_stat

- name: 读取 front-proxy-ca 根证书 stat 信息
  stat: 
    path: /etc/kubernetes/pki/front-proxy-ca.crt
  register: front_proxy_ca_crt_stat

- name: 读取 apiserver 证书私钥 stat 信息
  stat: 
    path: /etc/kubernetes/pki/apiserver.key
  register: apiserver_key_stat

- name: 读取 apiserver-kubelet-client 证书私钥 stat 信息
  stat: 
    path: /etc/kubernetes/pki/apiserver-kubelet-client.key
  register: apiserver_kubelet_client_key_stat

- name: 读取 front-proxy-client 证书私钥 stat 信息
  stat: 
    path: /etc/kubernetes/pki/front-proxy-client.key
  register: front_proxy_client_key_stat

- name: 读取 kube-scheduler 证书私钥 stat 信息
  stat: 
    path: /etc/kubernetes/pki/kube-scheduler.key
  register: kube_scheduler_key_stat

- name: 读取 sa 证书私钥 stat 信息
  stat: 
    path: /etc/kubernetes/pki/sa.key
  register: sa_key_stat

- name: 读取 sa 证书公钥 stat 信息
  stat: 
    path: /etc/kubernetes/pki/sa.pub
  register: sa_pud_stat

- name: 读取 admin 证书私钥 stat 信息
  stat: 
    path: /etc/kubernetes/pki/admin.key
  register: admin_key_stat

- name: 读取 kubelet 证书私钥 stat 信息
  stat: 
    path: /etc/kubernetes/pki/kubelet.key
  register: kubelet_key_stat