- name: Haproxy | 生成 haproxy 配置文件
  template: 
    src: haproxy/haproxy.cfg.j2 
    dest: /etc/kubernetes/plugins/lb-config/haproxy.cfg
    owner: root
    mode: 0644
  register: lb_configuration_result

- name: Haproxy | 生成 haproxy static pod 文件
  template: 
    src: haproxy/haproxy.yaml.j2
    dest: /etc/kubernetes/manifests/lb-kube-apiserver.yaml
    owner: root
    mode: 0644

- name: Haproxy | 拉取相关镜像
  shell: docker pull {{ item }}
  with_items:
  - "{{ lb_haproxy_image }}"
  - "{{ pod_infra_container_image }}"
  when: install_mode == 'online'