- name: Nginx lb | 生成 nginx lb 配置文件
  template:
    src: nginx/nginx.conf.j2
    dest: /etc/kubernetes/plugins/lb-config/nginx.conf
    owner: root
    mode: 0644
  register: lb_configuration_result

- name: Nginx lb | 生成 nginx lb static pod 文件
  template:
    src: nginx/nginx.yaml.j2
    dest: /etc/kubernetes/manifests/lb-kube-apiserver.yaml
    owner: root
    mode: 0644

- name: Nginx lb | 拉取相关镜像
  shell: docker pull {{ item }}
  with_items:
  - "{{ lb_nginx_image }}"
  - "{{ pod_infra_container_image }}"
  when: install_mode == 'online'