- name: 创建 kubelet 相关目录
  file: 
    name: "{{ item }}"
    state: directory
  with_items:
  - "{{ kubelet_root_dir }}"
  - /etc/systemd/system/kubelet.service.d

- block:
  - name: 在 etcd 节点创建 etcd 相关目录
    file: 
      name: "{{ item }}"
      state: directory
    with_items:
    - "{{ etcd_data_dir }}"
    - "{{ etcd_backup_dir }}"
    - /etc/kubernetes/pki/etcd
    - /etc/kubernetes/manifests

  - name: 在 etcd 节点拉取相关镜像
    shell: docker pull {{ item }}
    with_items:
    - "{{ etcd_image }}"
    - "{{ pod_infra_container_image }}"
    when: install_mode == 'online'

  when: inventory_hostname in (groups['etcd'] + groups['new-etcd'])

- name: 在 master 节点创建 etcd 证书相关目录
  file: 
    name: /etc/kubernetes/pki/etcd
    state: directory
  when: inventory_hostname in (groups['kube-master'] + groups['new-master'])

- block:
  # 获取密钥状态
  - include_tasks: certificate/certs_stat.yml
  # 生成证书
  - include_tasks: certificate/generate.yml
  when: inventory_hostname == groups['etcd']|first

# 分发证书
- include_tasks: certificate/distribute.yml

- block:
  - name: 读取 etcd static pod yaml 文件 stat 信息
    stat: 
      path: /etc/kubernetes/manifests/etcd-external.yaml
    register: etcd_static_pod_stat

  - name: 生成 etcd static pod 文件
    template: 
      src: etcd-external.yaml.j2
      dest: /etc/kubernetes/manifests/etcd-external.yaml
      owner: root
      mode: 0644
    when: not etcd_static_pod_stat.stat.exists
  when: inventory_hostname in (groups['etcd'] + groups['new-etcd'])

- name: 读取 kubelet.conf 文件 stat 信息
  stat: 
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf_stat

- block:
  - name: 获取 Docker Cgroup Driver 值
    shell: docker info --format '{{ '{{' }} json .CgroupDriver {{ '}}' }}' | cut -d'"' -f2
    register: docker_cgroup_driver
  
  - name: 设置变量 DOCKER_CGROUP_DRIVER
    set_fact: DOCKER_CGROUP_DRIVER="{{ docker_cgroup_driver.stdout }}"

  - name: 生成临时 kubelet unit 文件
    template: 
      src: 20-kubelet-override.conf.j2
      dest: "/etc/systemd/system/kubelet.service.d/20-kubelet-override.conf"
      owner: root
      mode: 0644

  - name: 重新加载 daemon
    systemd:
      daemon_reload: yes

  - name: 临时启动 kubelet 以引导 etcd 运行
    service:
      name: kubelet
      state: restarted
      enabled: yes

  when: 
  - inventory_hostname in (groups['etcd'] + groups['new-etcd'])
  - not kubelet_conf_stat.stat.exists

- name: 校验新添加的 etcd 节点是否已在 etcd 集群中
  shell: >
    docker run --name etcd-healthcheck --net host -e ETCDCTL_API=3 
    -v /etc/kubernetes/pki/etcd:/etc/kubernetes/pki/etcd
    --rm {{ etcd_image }}
    etcdctl 
    --endpoints=https://[127.0.0.1]:2379
    --cacert=/etc/kubernetes/pki/etcd/ca.crt
    --key=/etc/kubernetes/pki/etcd/healthcheck-client.key
    --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt
    member list
  register: etcd_member_list
  delegate_to: "{{ groups['etcd']|first }}"
  when: inventory_hostname in groups['new-etcd']

- name: 将新添加的 etcd 节点添加到 etcd 集群中
  shell: >
    docker run --name etcd-healthcheck --net host -e ETCDCTL_API=3 
    -v /etc/kubernetes/pki/etcd:/etc/kubernetes/pki/etcd
    --rm {{ etcd_image }}
    etcdctl 
    --endpoints=https://[127.0.0.1]:2379
    --cacert=/etc/kubernetes/pki/etcd/ca.crt
    --key=/etc/kubernetes/pki/etcd/healthcheck-client.key
    --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt
    member add {{ NEW_MEMBER }}
  delegate_to: "{{ groups['etcd']|first }}"
  when: 
  - inventory_hostname in groups['new-etcd']
  - inventory_hostname not in etcd_member_list.stdout

- name: 以轮询的方式等待 etcd 运行完成
  shell: >
    docker run --name etcd-healthcheck --net host -e ETCDCTL_API=3 
    -v /etc/kubernetes/pki/etcd:/etc/kubernetes/pki/etcd
    --rm {{ etcd_image }}
    etcdctl 
    --endpoints=https://[127.0.0.1]:2379
    --cacert=/etc/kubernetes/pki/etcd/ca.crt
    --key=/etc/kubernetes/pki/etcd/healthcheck-client.key
    --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt
    endpoint health
  register: etcd_status
  until: '"is healthy" in etcd_status.stdout'
  retries: 12
  delay: 5
  when: inventory_hostname in (groups['etcd'] + groups['new-etcd'])
  
- block:
  - name: 移除临时 kubelet unit 文件
    file: 
      name: "{{ item }}"
      state: absent
    with_items:
    - /etc/systemd/system/kubelet.service.d/20-kubelet-override.conf
  - name: 重新加载 daemon
    systemd:
      daemon_reload: yes
  - name: 停止临时启动 kubelet
    service:
      name: kubelet
      state: stopped
      enabled: yes
  when: 
  - inventory_hostname in (groups['kube-master'] + groups['kube-worker'] + groups['new-master'] + groups['new-worker']) 
  - not kubelet_conf_stat.stat.exists

- block:
  - name: 第一个 etcd 节点创建 etcd 定时备份 crontab
    cron: 
      minute: "0"
      hour: "{{ etcd_backup_hour }}"
      name: Backup etcd databases
      job: >
        docker run --name etcd-backup --net host -e ETCDCTL_API=3
        -v {{ etcd_backup_dir }}:/snapshot
        -v /etc/kubernetes/pki/etcd/:/etc/kubernetes/pki/etcd/
        --rm {{ etcd_image }}
        etcdctl snapshot save 
        /snapshot/etcd-snapshot-$(date -Iseconds).db 
        --cacert=/etc/kubernetes/pki/etcd/ca.crt 
        --key=/etc/kubernetes/pki/etcd/healthcheck-client.key 
        --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt
  - name: 第一个 etcd 节点创建清理 etcd 定时备份文件 crontab
    cron: 
      minute: "0"
      hour: "{{ etcd_backup_hour }}"
      name: Clean etcd databases backup file
      job: >
        find {{ etcd_backup_dir }} -ctime +{{ etcd_backup_expiry }} -name 'etcd-snapshot*.db' | xargs rm -rf
  when: inventory_hostname == groups['etcd']|first