- name: 准备 Docker 相关目录
  file: 
    name: "{{ item }}"
    state: directory
  with_items:
  - /etc/docker
  - "{{ docker_storage_dir }}"

- name: 确认 Docker 配置是否有修改
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    mode: 0644
  register: configuration_result

- name: 重新加载 daemon
  systemd:
    daemon_reload: yes

- block:
  - name: 清理 iptables
    shell: >
      iptables -F &&
      iptables -X &&
      iptables -F -t nat &&
      iptables -X -t nat &&
      iptables -F -t raw &&
      iptables -X -t raw &&
      iptables -F -t mangle &&
      iptables -X -t mangle

  - name: 启动/重启 Docker
    service:
      name: docker
      state: restarted
      enabled: yes
  when: 
  - configuration_result.changed
  - '"active" not in docker_already_running.stdout'

- block:
  - name: 需手动重启 Docker 
    vars: 
      msg: |
        节点：{{ inventory_hostname }} ，Docker 处于运行中，
        但 Docker 配置文件 /etc/docker/daemon.json 已更新，
        请在集群安装完成后手动执行下面命令重启该节点 docker 与 kubelet：
            systemctl restart docker
            systemctl restart kubelet
        
        若重启后 kubelet 无法正常启动：
        请确认以下两个文件中 cgroup driver 参数是否设置为 systemd，
        若不是则修改为 systemd 后再次重启 kubelet。
            vi /var/lib/kubelet/config.yaml
            vi /var/lib/kubelet/kubeadm-flags.env
        在 /var/lib/kubelet/config.yaml 文件中参数名为：cgroupDriver；
        在 /var/lib/kubelet/kubeadm-flags.env 文件中参数名为：--cgroup-driver，若参数不存在请忽略。

    debug: 
      msg: "{{ msg.split('\n') }}"

  - name: 等待用户查看日志
    shell: sleep 60
    run_once: true
  when: 
  - configuration_result.changed
  - '"active" in docker_already_running.stdout'

- name: 设置 Docker 开机自启
  service:
    name: docker
    state: started
    enabled: yes

- name: 添加当前用户到 Docker 用户组
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes