# - name: 删除centos默认安装
#   yum: 
#     name: 
#     - firewalld
#     - python-firewall
#     - firewalld-filesystem
#     state: absent
#     disablerepo: "*"

- block:
  - name: 判断 firewalld 是否安装
    shell: >
      systemctl status firewalld | grep active || echo "not be found"
    register: firewalld_already_installed
  
  - name: 禁用防火墙
    service:
      name: firewalld
      state: stopped
      enabled: no
    when: '"active" in firewalld_already_installed.stdout'
  when: "(firewalld_disabled | bool) | default(true)"

- name: 设置 yum obsoletes 值为 0
  lineinfile:
    path: /etc/yum.conf
    regexp: '^obsoletes'
    line: obsoletes=0

- name: 清除 yum 缓存
  command: yum clean all
  args:
    warn: no

- block:
  - name: 备份原有 yum 源
    shell: mv /etc/yum.repos.d /etc/yum.repos.d.orig.$(date '+%Y%m%dT%H%M%S')
    ignore_errors: true

  - name: 创建相关目录
    file:
      path: /etc/yum.repos.d
      state: directory

  - name: 添加基础 yum 仓库
    yum_repository:
      name: base
      description: Custom Repository
      baseurl: "{{ base_yum_repo }}"
      enabled: yes
      gpgcheck: no
      state: present
  when: base_yum_repo is defined and base_yum_repo != None

- name: 添加 epel 仓库
  yum_repository:
    name: epel
    file: epel
    description: Extra Packages for Enterprise Linux $releasever - $basearch
    baseurl: "{{ epel_yum_repo }}"
    enabled: yes
    gpgcheck: no
    state: present

- name: 安装基础软件包
  yum: 
    name: 
    - jq                              # 轻量JSON处理程序
    - git
    - htop
    - lvm2                            # docker会用到
    - curl                            # 基础工具
    - audit
    - iotop
    - ipset                           # ipvs 模式需要
    - socat                           # 用于port forwarding
    - sysstat
    - ipvsadm                         # ipvs 模式需要
    - nmap-ncat                       # 使用lb时进行端口判断时会用到
    - nfs-utils                       # 挂载nfs 共享文件需要 (创建基于 nfs的 PV 需要)
    - yum-utils                       # 基础工具
    - net-tools
    - libseccomp
    - conntrack-tools                 # ipvs 模式需要
    - bash-completion                 # bash命令补全工具，需要重新登录服务器生效
    - device-mapper-persistent-data   # docker会用到
    state: latest

- name: 重新启动 crond 避免因修改时区而导致的作业错乱问题
  service:
    name: crond
    state: restarted
    enabled: yes

- name: 临时关闭 selinux
  shell: "setenforce 0"
  failed_when: false

- name: 永久关闭 selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"