# # 删除默认安装
# - name: 删除ubuntu默认安装
#   apt: 
#     name: 
#       - ufw
#       - lxd
#       - lxd-client
#       - lxcfs
#       - lxc-common
#     state: absent

- block:
  - name: 判断 ufw 是否安装
    shell: >
      systemctl is-active ufw | grep active || echo "not be found"
    register: ufw_already_installed
  
  - name: 禁用防火墙
    service:
      name: ufw
      state: stopped
      enabled: no
    when: ufw_already_installed.stdout == "active"
  when: "(firewalld_disabled | bool) | default(true)"

# - name: iptables 工具切换到 “旧版” 模式
#   shell: "{{ item }} || true"
#   with_items:
#   - update-alternatives --set iptables /usr/sbin/iptables-legacy
#   - update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
#   - update-alternatives --set arptables /usr/sbin/arptables-legacy
#   - update-alternatives --set ebtables /usr/sbin/ebtables-legacy
#   when: 
#   - >-
#     (ansible_distribution == "Debian" and ansible_distribution_version is version('10', '>=')) or
#     (ansible_distribution == "Ubuntu" and ansible_distribution_version is version('19', '>='))
#   - "(nftables_to_iptables | bool) | default(false)" 

- name: 添加基础 Apt 仓库
  apt_repository:
    repo: "{{ base_apt_repo }}"
    state: present
  when: base_apt_repo is defined and base_apt_repo != None
  
# Ubuntu 安装基础软件包
- name: 安装 ubuntu 基础软件
  apt: 
    name:
    - jq                          # 轻量JSON处理程序，安装docker查询镜像需要
    - git
    - htop
    - curl                        # 基础工具
    - lvm2                        # docker会用到
    - socat                       # 用于port forwarding
    - ipset                       # ipvs 模式需要
    - iotop
    - sysstat
    - ipvsadm                     # ipvs 模式需要
    - conntrack                   # network connection cleanup 用到
    - net-tools
    - nfs-common                  # 挂载nfs 共享文件需要 (创建基于 nfs的PV 需要)
    - libseccomp2                 # 安装containerd需要
    - netcat-openbsd              # 使用lb时进行端口判断时会用到
    - ca-certificates             # docker会用到
    - bash-completion             # bash命令补全工具，需要重新登录服务器生效
    - apt-transport-https         # 添加https协议的apt源会用到
    - software-properties-common  # docker会用到
    state: present
    update_cache: yes
    allow_unauthenticated: true

- name: 重新启动 cron 避免因修改时区而导致的作业错乱问题
  service:
    name: cron
    state: restarted
    enabled: yes