- name: 升级 linux-base
  apt:
    deb: "{{ item }}"
  with_items: "{{ linux_base }}"
  when: ansible_distribution in [ 'Debian' ]

- name: 安装 kernel-ml
  apt:
    deb: "{{ item }}"
  with_items: "{{ kernel_ubuntu }}"

- name: 更新 grub
  shell: update-grub
  ignore_errors: true