name: Docker images for arm64
on:
  workflow_call:
    secrets:
      OSS_TOKEN:
      OSS_USERNAME:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install and configure minio client
      run: |
        sudo curl -sSLo /usr/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc
        sudo chmod +x /usr/bin/mc
        mc alias set oss https://oss.choerodon.com.cn ${{ secrets.OSS_USERNAME }} ${{ secrets.OSS_TOKEN }}

    - name: Download images for arm64
      run: |
        docker system prune -a -f --volumes
        docker run -d -p 5000:5000 --name registry \
          -v $PWD/registry:/var/lib/registry \
          registry:2
        /bin/bash offline/download-images.sh linux/arm64
        tar -czvf registry.tgz registry

    - name: Upload arm64 artifact to oss
      id: oss
      run: |
        mc cp --json registry.tgz oss/kubeadm-ha/kubernetes-1.30.5-images-arm64.tgz 2>&1 | tee oss.log
        target=$(cat oss.log | jq -r 'select(.target)|.target')
        echo "::warning file=kubernetes-images::https://oss.choerodon.com.cn/${target#*/}"
