name: ci
on:
  push:
    branches-ignore:
    - 'master'
jobs:
  sync1:
    runs-on: ubuntu-latest
    container: setzero/images-sync:0.2.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync images
        run: |
          set -exu
          image_list="
          openresty/openresty:1.17.8.2-alpine
          nginx:1.18-alpine
          haproxy:2.1-alpine
          envoyproxy/envoy:v1.16.0
          osixia/keepalived:2.0.20
          quay.io/coreos/flannel:v0.13.0
          calico/typha:v3.16.5
          calico/cni:v3.16.5
          calico/node:v3.16.5
          calico/kube-controllers:v3.16.5
          calico/pod2daemon-flexvol:v3.16.5
          calico/ctl:v3.16.5
          k8s.gcr.io/ingress-nginx/controller:v0.41.0
          jettech/kube-webhook-certgen:v1.5.0
          traefik:2.3.1
          kubernetesui/dashboard:v2.0.4
          kubernetesui/metrics-scraper:v1.0.4
          k8s.gcr.io/metrics-server/metrics-server:v0.4.0
          quay.io/jetstack/cert-manager-cainjector:v1.0.4
          quay.io/jetstack/cert-manager-webhook:v1.0.4
          quay.io/jetstack/cert-manager-controller:v1.0.4
          "
          
          new_docker_registry=${NEW_DOCKER_REGISTRY:-'registry.cn-shanghai.aliyuncs.com/kubeadm-ha'}
          for image in $image_list ; do 
            count=$(echo $image | grep -o '/*' | wc -l)
            if [ $count -eq 0 ]
            then
              new=$new_docker_registry/$image
            elif [ $count -eq 1 ]
            then
              new=$new_docker_registry/$(echo ${image} | sed 's / _ g')
            else
              new=$new_docker_registry/$(echo ${image#*/} | sed 's / _ g')
            fi
            skopeo copy --all --dest-creds ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }} \
            docker://$image docker://$new
          done

  sync2:
    runs-on: ubuntu-latest
    container: setzero/images-sync:0.2.0
    steps:
      - name: Sync images
        run: |
          set -exu
          for tag in $(skopeo list-tags docker://k8s.gcr.io/kube-proxy | jq -r .Tags[] | grep -Ev 'alpha|beta|rc'); 
          do
            skopeo copy --all --dest-creds ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }} \
            docker://k8s.gcr.io/kube-proxy:${tag} docker://registry.cn-shanghai.aliyuncs.com/kubeadm-ha/kube-proxy:${tag}; 
          done

          for tag in $(skopeo list-tags docker://k8s.gcr.io/kube-controller-manager | jq -r .Tags[] | grep -Ev 'alpha|beta|rc|fda24638d51a48baa13c35337fcd4793'); 
          do
            skopeo copy --all --dest-creds ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }} \
            docker://k8s.gcr.io/kube-controller-manager:${tag} docker://registry.cn-shanghai.aliyuncs.com/kubeadm-ha/kube-controller-manager:${tag}; 
          done

          for tag in $(skopeo list-tags docker://k8s.gcr.io/kube-apiserver | jq -r .Tags[] | grep -Ev 'alpha|beta|rc|9680e782e08a1a1c94c656190011bd02'); 
          do
            skopeo copy --all --dest-creds ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }} \
            docker://k8s.gcr.io/kube-apiserver:${tag} docker://registry.cn-shanghai.aliyuncs.com/kubeadm-ha/kube-apiserver:${tag}; 
          done

          for tag in $(skopeo list-tags docker://k8s.gcr.io/kube-scheduler | jq -r .Tags[] | grep -Ev 'alpha|beta|rc|34d0b8f8b31e27937327961528739bc9'); 
          do
            skopeo copy --all --dest-creds ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }} \
            docker://k8s.gcr.io/kube-scheduler:${tag} docker://registry.cn-shanghai.aliyuncs.com/kubeadm-ha/kube-scheduler:${tag}; 
          done

          for tag in $(skopeo list-tags docker://k8s.gcr.io/coredns | jq -r .Tags[] | grep -v '__'); 
          do
            skopeo copy --all --dest-creds ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }} \
            docker://k8s.gcr.io/coredns:${tag} docker://registry.cn-shanghai.aliyuncs.com/kubeadm-ha/coredns:${tag}; 
          done

          for tag in $(skopeo list-tags docker://k8s.gcr.io/pause | jq -r .Tags[] | grep -E '^\d\.\d$'); 
          do
            skopeo copy --all --dest-creds ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }} \
            docker://k8s.gcr.io/pause:${tag} docker://registry.cn-shanghai.aliyuncs.com/kubeadm-ha/pause:${tag}; 
          done
