name: ci
on:
  push:
    branches-ignore:
    - 'master'
jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        run: |
          set -exu
          image_list="
          openresty/openresty:1.17.8.2-alpine
          nginx:1.18-alpine
          haproxy:2.1-alpine
          envoyproxy/envoy:v1.16.0
          osixia/keepalived:2.0.20
          quay.io/coreos/flannel:v0.13.0
          calico/typha:v3.16.5
          calico/cni:v3.16.5
          calico/node:v3.16.5
          calico/kube-controllers:v3.16.5
          calico/pod2daemon-flexvol:v3.16.5
          calico/ctl:v3.16.5
          k8s.gcr.io/ingress-nginx/controller:v0.41.0
          jettech/kube-webhook-certgen:v1.5.0
          traefik:2.3.1
          kubernetesui/dashboard:v2.0.4
          kubernetesui/metrics-scraper:v1.0.4
          k8s.gcr.io/metrics-server/metrics-server:v0.4.0
          quay.io/jetstack/cert-manager-cainjector:v1.0.4
          quay.io/jetstack/cert-manager-webhook:v1.0.4
          quay.io/jetstack/cert-manager-controller:v1.0.4
          "
          
          new_docker_registry=${NEW_DOCKER_REGISTRY:-'registry.cn-shanghai.aliyuncs.com/kubeadm-ha'}
          for image in $image_list ; do 
            count=$(echo $image | grep -o '/*' | wc -l)
            if [ $count -eq 0 ]
            then
              new=$new_docker_registry/$image
            elif [ $count -eq 1 ]
            then
              new=$new_docker_registry/$(echo ${image} | sed 's / _ g')
            else
              new=$new_docker_registry/$(echo ${image#*/} | sed 's / _ g')
            fi
            echo "FROM $image" > Dockerfile
            /usr/bin/docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file ./Dockerfile --push . \
            --tag $new
          done
